name: validate
on:
  push:
    branches: [ master ]

jobs:
  build:
    container: gkarthics/swagger-validate:0.2.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate
      run: validate . ./json
